#!/bin/bash
set -e

usage() {
	echo "usage: mmail enable|disable FEATURE"
	echo "see man mmail(1)"
}

# files
maincf="/etc/postfix/main.cf"
contfilt="/etc/postfix/mmail/mmail.contfilt.regexp"

# check parameters
if [ $# -ne 2 ]
then
	echo "error: invalid parameter count"
	usage
	exit 1
fi
case "$1" in
enable) ;;
disable) ;;
*)
	echo "error: invalid 1st parameter"
	usage
	exit 1
esac

# check privileges
if [ $(id -u) -ne 0 ]
then
	echo "Run this script with root privileges!"
	exit 1
fi

# check system

# TODO: Das geht auf Debian7 nicht (RC1)
sctl=$(which systemctl) || sctl=$(which sysd2sysv) || (echo "install sysd2sysv"; exit 1)

# stop postfix
$sctl stop postfix

case "$2" in
amavis-vt)
	if ! dpkg -l | grep mmail-vt
	then
		echo "Error: Install mmail-vt!"
		exit 1
	fi

	$sctl stop amavisd-new
	case "$1" in
	enable) 
		if ! test -f /etc/amavis/conf.d/56-mmail_scanners
		then 
			cp /etc/amavis/conf.d/55-mmail_filter_mode.example /etc/amavis/conf.d/55-mmail_filter_mode
			cp /etc/amavis/conf.d/56-mmail_scanners.example /etc/amavis/conf.d/56-mmail_scanners
		fi
		;;
	disable)
		rm /etc/amavis/conf.d/55-mmail_filter_mode || true
		rm /etc/amavis/conf.d/56-mmail_scanners || true
		;;
	esac
	$sctl start amavisd-new
	;;
e2e-in)
	commenter.pl $contfilt EEI $1
	case "$1" in
	enable) 
		$sctl start decryptd
		$sctl enable decrypd
		;;
	disable)
		$sctl stop decryptd
		$sctl disable decryptd
		;;
	esac
	;;
mlist)
	case "$1" in
	enable)
		echo "Installing mlist feature"
		if [ -n "$(postconf -h smtpd_recipient_restrictions |grep mlist.contfilt.regexp)" ]
		then
			echo "mlist already installed"
		else
			postconf smtpd_recipient_restrictions="check_recipient_access regexp:/etc/postfix/mmail/mlist.contfilt.regexp $(postconf -h smtpd_recipient_restrictions)"
		fi
		$sctl start mlistd
		$sctl enable mlistd
		;;
	disable)
		echo "Deinstalling mlist feature"
		restr=$(postconf -h smtpd_recipient_restrictions |sed "s!check_recipient_access regexp:/etc/postfix/mmail/mlist.contfilt.regexp!!")
		postconf smtpd_recipient_restrictions="$restr"
		$sctl stop mlistd
		$sctl disable mlistd
		;;
	esac
	;;
tls-out)
	commenter.pl $maincf TO $1
	case "$1" in
	enable)
		if test "$(postmulti -l -i postfix-smtp-tls |wc -l) -eq 1"
		then
			postmulti -e enable -i postfix-smtp-tls
		else
			postmulti -e create -I postfix-smtp-tls config_directory=/etc/postfix/smtp-tls
		fi
		;;
	disable)
		postmulti -e disable -i postfix-smtp-tls
		postmulti -e deport -i postfix-smtp-tls
		;;
	esac

	;;
*)
	echo "error: invalid FEATURE"
	usage
	exit 1
esac

# start postfix
$sctl start postfix || true

