#!/bin/bash
set -e

usage() {
	echo "usage: mmail enable|disable FEATURE"
	echo "see man mmail(1)"
}

# files
maincf="/etc/postfix/main.cf"
contfilt="/etc/postfix/mmail/mmail.contfilt.regexp"

# check parameters
if [ $# -ne 2 ]
then
	echo "error: invalid parameter count"
	usage
	exit 1
fi
case "$1" in
enable) ;;
disable) ;;
*)
	echo "error: invalid 1st parameter"
	usage
	exit 1
esac

# check privileges
if [ $(id -u) -ne 0 ]
then
	echo "Run this script with root privileges!"
	exit 1
fi

# stop postfix
/etc/init.d/postfix stop

case "$2" in
e2e-in)
	commenter.pl $contfilt EEI $1
	case "$1" in
	enable) 
		/etc/init.d/decryptd start
		update-rc.d decryptd defaults 100
		;;
	disable)
		/etc/init.d/decryptd stop
		update-rc.d -f decryptd remove
		;;
	esac
	;;
tls-out)
	commenter.pl $maincf TO $1
	case "$1" in
	enable)
		if test "$(postmulti -l -i postfix-smtp-tls |wc -l) -eq 1"
		then
			postmulti -e enable -i postfix-smtp-tls
		else
			postmulti -e create -I postfix-smtp-tls config_directory=/etc/postfix/smtp-tls
		fi
		;;
	disable)
		postmulti -e disable -i postfix-smtp-tls
		postmulti -e deport -i postfix-smtp-tls
		;;
	esac

	;;
*)
	echo "error: invalid FEATURE"
	usage
	exit 1
esac

# start postfix
/etc/init.d/postfix start

