.\" Manpage for mmail-vt.
.\" Contact mail@wagnertech.de to correct errors or typos.
.TH man 8 "13 Sep 2017" "1.0" "mmail man page"
.SH NAME
mmail\-vt \- virus total extension for postfix / amavisd-new
.SH DESCRIPTION
mmail-vt is a perl\-amavisd-new\-plugin. After installing the debian package it is enabled by default.
To disable this feature remove TODO or use the mmail(8) feature from the mmail package.
.SH SEE ALSO
mmail(8), postfix(8), amavisd-new(8)
.SH FILES
TODO
.SH BUGS
No known bugs
.SH AUTHOR
Michael Wagner (michael@wagnertech.de)
