.\" Manpage for update-mlist.
.\" Contact mail@wagnertech.de to correct errors or typos.
.TH man 1 "22 Feb 2018" "1.0" "update-mlist man page"
.SH NAME
update-mlist \- update existing mailling list
.SH SYNOPSIS
.B update-mlist
.SH DESCRIPTION
.PP
If a file containing email addresses for a mailling list is updated, this update has to be
activated by this command.
.SH SEE ALSO
mmail(8), announce-mlist(1)
.SH AUTHOR
Michael Wagner (michael@wagnertech.de)
